name: Pipeline CI/CD - Architect Python API (Docker Registry Test)

on:
  push:
    branches: [ main ]

jobs:
  build-test-and-local-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instalar dependencias locales de prueba
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Validar sintaxis con Flake8
      run: |
        # Validamos que tu main.py no tenga errores de sintaxis
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Iniciar Registro Local de Docker
      run: |
        # Levantamos un registro Docker oficial y gratuito en el puerto 5000
        docker run -d -p 5000:5000 --name registro-local registry:2
        
        echo "Esperando 5 segundos para inicializar el registro..."
        sleep 5

    - name: Construir Imagen de Docker de tu API
      run: |
        # Construimos la imagen usando tu Dockerfile real
        docker build -t mi-api-fastapi:latest .

    - name: Taggear y Empujar la Imagen al Registro Local
      run: |
        # Taggeamos la imagen apuntando a nuestro registro local en el puerto 5000
        docker tag mi-api-fastapi:latest localhost:5000/mi-api-fastapi-repo:latest
        
        # Subimos la imagen para simular el "push" de AWS ECR
        docker push localhost:5000/mi-api-fastapi-repo:latest
        echo "¡Imagen de FastAPI subida con éxito al registro simulado!"
